AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Digit-Eyes-App

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  RequestProductDetailsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/request_product_details/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Environment:
          Variables:
            BASE_URI: "https://www.digit-eyes.com/gtin/v2_0/"
            LANGUAGE: "en"
            DIGITEYES_KEY: "XXXXX"
      Events:
        RequestProductDetails:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /lookup
              Method: get