AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digit_eyes_client

  Sample SAM Template for digit_eyes_client

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  RequestProductDetailsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/request_product_details/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Environment:
          Variables:
            GEM_PATH: /opt/ruby/2.7.0
            BASE_URI: 'https://www.digit-eyes.com/gtin/v2_0/'
            LANGUAGE: "en"
            DIGITEYES_KEY: "XXXX"
      Layers:
        - !Ref libs

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: digit-eyes-lib
      Description: Dependencies for the digit eyes app.
      ContentUri: ./functions/utils/.
      CompatibleRuntimes:
        - ruby2.7
